### ISSUE TITLE
press the "refresh status" button

### ISSUE THREAD

**Issue by kcferguson1** [0x111/servicenow-instance-wakeup#10]
after navigating to this page, https://developer.servicenow.com/app.do#!/instance?wu=true
can you have the script push the "refresh status" button?

**Comment by 0x111** [comment]
Hi @kcferguson1 the purpose of this app is to reduce the amount of manual tasks needed to wake up your instance. I certainly do not want to somehow go against the rules or around them. That is why my intention is to keep this as simple as possible and concentrate on the reducing of the manual tasks.

So technically it is possible, but this does not relate to the purposes of this app.
