### ISSUE TITLE
Errors while executing on a headless node

### ISSUE THREAD

**Issue by termlen0** [0x111/servicenow-instance-wakeup#13]
Hello,

I am running the binary as follows:
```
./servicenow-instance-wakeup-linux-amd64 -username username@site.com -password mypassword  -headless -debug
```

From the debug:

```
{"method":"Target.receivedMessageFromTarget","params":{"sessionId":"5BA1B278B31922A65ADF5F1AFAA3984D","message":"{\"error\":{\"code\":-32000,\"message\":\"Could not compute box model.\"},\"id\":10929}","targetId":"789178E05B163391DC942D671B33FFDE"}}

```
The exit code is 1.

**Comment by 0x111** [comment]
Hi @termlen0,
Thank you for using the app. 
~~Try to define the parameters like described in the readme please. https://github.com/0x111/servicenow-instance-wakeup/blob/master/README.md~~
~~So for your command:
`./servicenow-instance-wakeup-linux-amd64 -username=username@site.com -password=mypassword -headless=true -debug=true`~~
Also, could you provide more debug output? (There should be more than this one line there if the debug is on)
Edit: Also do you have chrome installed?
Edit2: I just did a try, the parameters should be fine like you've described them, so let's strike that through.
I also did a test run here, and it seems to be navigating through the pages in headless mode, so it really may be an issue with the chrome version you are using, let me know please. Sorry for the initial confusion

**Comment by termlen0** [comment]
Appreciate the feedback.. So trying again, looks like the binary actually works, but the exit code is non-zero. As for the debugs, there are pages and pages of output. Was hoping that one was relevant :)

**Comment by 0x111** [comment]
That is the debug output of the chrome headless mode itself. The error you posted is something rather chrome related, but like you've said, there is a lot of small errors or warnings if we render any page with the debug mode on.

Except of the non-zero exit code, which I understand might be confusing in the context of CLI apps, is there something I can help you with? :)

PS: I just did a brief test with the latest binary myself, seems to be doing what it is supposed to.

**Comment by termlen0** [comment]
Fair enough. Closing
