### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by FracKenA** [0x111/servicenow-instance-wakeup#15]
I have created a PR for a docker image using the chromedp/headless-shell image that resolves all dependencies and will simply work. 

IF you want to simplify this even further you could create an automated build process on docker hub from this repo and with each update, it will build a later release for you. I have completed a test that can be tested and verified at 

https://hub.docker.com/r/frackena/servicenowinstancewakup

this would enable doing the following without the need for users to perform a build themselves while enabling the image to stay 100% up to date without the external intervention of having to do a PR out to my repo.
`docker pull 0x111/servicenowinstancewakup`
`docker run -e USERNAME='YOUR_USERNAME@YOUR_DOMAIN.com' -e PASSWORD='YOUR_SERVICENOW_DEVELOPER_PASSWORD' 0x111/servicenowinstancewakup`

**Comment by 0x111** [comment]
Hi @FracKenA, thank you for your contribution and time! I appreciate your effort!

I will review this, but in the very generic view it makes a lot of sense to have this and I agree with your proposition :).
I did use docker hub in the past, now that github offers also docker packages, are there any disadvantages of using github packages for distribution and opting for docker hub instead?

I remember that in the past, we had many 3rd party tools like travis, circleci, npmjs and many other on distributing these stuff, but having an overview of all these at once seemed always a mess to me, that is why I am asking about also your opinion. (Others are welcome to chime in too)

We are already using github actions here, so I guess it would make sense to stay on github as much as possible, but I am also open to other things if there are any advantages to it.

**Comment by FracKenA** [comment]
Both are good options. The answer comes from end-user simplicity. 

when you type docker pull XXX/XXX it is always docker hub by default. For everything else, you have to use URL, create a new registry in docker, etc. 

In the end, the delivery method is not important, just the experience conveyed to end-users. 

One other key point I am uncertain of, does the Github registry support multistage builds?

**Comment by 0x111** [comment]
No mention about the multistage builds, but I agree with your arguments. It is more user friendly if we use docker hub for now and we will see in the future if we need to adjust something.

I will try to look through this soon and let you know. Thanks for the feedback!

**Comment by 0x111** [comment]
Added in #16
