### ISSUE TITLE
Timeout error?

### ISSUE THREAD

**Issue by lukasz-kuch** [0x111/servicenow-instance-wakeup#19]
could not find shadow element (header status bar): context deadline exceeded

**Comment by 0x111** [comment]
Try to raise the timeout to a higher number please. Also ensure that if you are successfully logging in and are on the dev portal page at this step.

Try to run this without headless mode if you did not yet and see what happens.

**Comment by lukasz-kuch** [comment]
Unfortunately, still doesn't work. Headless change to 'false' and timeout set to higher number(60sec)

**Comment by 0x111** [comment]
More details would be needed, do you see the developer portal opening after login? Hard to tell from these details. Also chrome version would be useful possibly, provide screenshots what do you see when the app is exiting (redact unnecessary info)

**Comment by rgstephens** [comment]
Thanks for this package. I'm also running into this issue. Here's the last few lines of the log. Tried headless true & false.

```
servicenow-wakeup_1  | Login successful!
servicenow-wakeup_1  | Detecting the wakeup button element to determine if we are on the developer portal homepage...
servicenow-wakeup_1  | could not find shadow element (header status bar): context deadline exceeded
```

With debug:

```
servicenow-wakeup_1  | 2020/05/18 18:13:17 -> {"id":16180,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2","method":"DOM.requestNode","params":{"objectId":"{\"injectedScriptId\":12,\"id\":6200}"}}
servicenow-wakeup_1  | 2020/05/18 18:13:17 <- {"id":16180,"result":{"nodeId":255},"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2"}
servicenow-wakeup_1  | 2020/05/18 18:13:17 -> {"id":16181,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2","method":"DOM.getBoxModel","params":{"nodeId":255}}
servicenow-wakeup_1  | 2020/05/18 18:13:17 <- {"error":{"code":-32000,"message":"Could not compute box model."},"id":16181,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2"}
servicenow-wakeup_1  | 2020/05/18 18:13:17 -> {"id":16182,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2","method":"Runtime.evaluate","params":{"expression":"document.querySelector(\"body \u003e dps-app\").shadowRoot.querySelector(\"div \u003e main \u003e dps-home-auth\").shadowRoot.querySelector(\"div \u003e div \u003e div.instance-widget \u003e dps-instance-sidebar\").shadowRoot.querySelector(\"div \u003e div.dps-instance-sidebar-content.dps-instance-sidebar-content-instance-info \u003e div.dps-instance-sidebar-content-btn-group \u003e dps-button\").shadowRoot.querySelector(\"button\")","objectGroup":"console","includeCommandLineAPI":true,"awaitPromise":true}}
servicenow-wakeup_1  | 2020/05/18 18:13:17 <- {"id":16182,"result":{"result":{"type":"object","subtype":"node","className":"HTMLButtonElement","description":"button.dps-button.-primary.-sm","objectId":"{\"injectedScriptId\":12,\"id\":6201}"}},"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2"}
servicenow-wakeup_1  | 2020/05/18 18:13:17 -> {"id":16183,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2","method":"DOM.requestNode","params":{"objectId":"{\"injectedScriptId\":12,\"id\":6201}"}}
servicenow-wakeup_1  | 2020/05/18 18:13:17 <- {"id":16183,"result":{"nodeId":255},"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2"}
servicenow-wakeup_1  | 2020/05/18 18:13:17 -> {"id":16184,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2","method":"DOM.getBoxModel","params":{"nodeId":255}}
servicenow-wakeup_1  | 2020/05/18 18:13:17 <- {"error":{"code":-32000,"message":"Could not compute box model."},"id":16184,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2"}
servicenow-wakeup_1  | 2020/05/18 18:13:17 -> {"id":16185,"sessionId":"5667B07D0B2C5596EBC9DC7CCA4DDEB2","method":"Runtime.evaluate","params":{"expression":"document.querySelector(\"body \u003e dps-app\").shadowRoot.querySelector(\"div \u003e main \u003e dps-home-auth\").shadowRoot.querySelector(\"div \u003e div \u003e div.instance-widget \u003e dps-instance-sidebar\").shadowRoot.querySelector(\"div \u003e div.dps-instance-sidebar-content.dps-instance-sidebar-content-instance-info \u003e div.dps-instance-sidebar-content-btn-group \u003e dps-button\").shadowRoot.querySelector(\"button\")","objectGroup":"console","includeCommandLineAPI":true,"awaitPromise":true}}
servicenow-wakeup_1  | could not find shadow element (header status bar): context deadline exceeded
```

**Comment by 0x111** [comment]
You are all trying with the docker container. Could you please try this without and only with the binary? 

I am not saying that you are doing something wrong, sadly we can not really write tests for this app :/ that would help a lot in debugging.

I did just run this, just the binary (darwin-amd64) with headless=false and it did wake up the instance that I had asleep for a few days now because I did not use it. 

I've downloaded [this version](https://github.com/0x111/servicenow-instance-wakeup/releases/tag/v0.5) here to test it and provided with a config file.

Related: https://github.com/0x111/servicenow-instance-wakeup/pull/16

**Comment by rgstephens** [comment]
It does indeed work for me from the command line.

**Comment by 0x111** [comment]
@rgstephens Thank you very much! This means we have issues with the docker version. I will need to double check it, thank you! In the meanwhile please use the binaries! They are essentially easy to use too.

**Comment by 0x111** [comment]
Based on my initial debugs the chrome browser in the docker seems to hang at the login... 

I will need more time to investigate this, the worst case scenario will be to remove docker support fully if I am not able to fix this.

**Comment by 0x111** [comment]
As for a status update for everyone that is somehow affected.
I think I've identified the issue, so a PR will be created in the upcoming days and I will need some people to test the implementation.

**Comment by 0x111** [comment]
Please see the PR and give me some feedback there. Thank you to all who provided me the logs and information needed to take care of this issue!

I will wait for approximately a week after opening of the PR and then merge it if no objections.
