### ISSUE TITLE
Frame issue when running script

### ISSUE THREAD

**Issue by Marcachusetts** [0x111/servicenow-instance-wakeup#2]
Hi,

I am receiving a 'frame' issue when running the script. It launches to the login page but when it's time to pass the credentials, it just hangs. I have had random success with it passing them but have only been successful with it 2 out of maybe 20 times and even then, it does not make it to the wake up piece of the instance. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/46455402/51361400-9dbb5b80-1a9d-11e9-8a21-1e66706a059d.png)

**Comment by 0x111** [comment]
Hi, sorry for the late reply, somehow I did not had notfications turned on for this repository (no idea), could you provide more details, are you running this in headless mode is this the debug output?

**Comment by Marcachusetts** [comment]
I believe I was, I will test again this morning and let you know. Thanks
for reaching back out to me!

**Comment by 0x111** [comment]
Hi @Marcachusetts did you had any time to review? Also please note, there is a new version avaliable, so if you had no chance to test it yet, maybe you could try it with the new version please?
[v0.2](https://github.com/0x111/servicenow-instance-wakeup/releases/tag/v0.2)

**Comment by 0x111** [comment]
ping @Marcachusetts you can also try v0.3 instead of v0.2

**Comment by 0x111** [comment]
I am closing this for lack of response from the reporter. If you ever get back to this @Marcachusetts feel free to reopen if it is still not working correctly.

**Comment by Marcachusetts** [comment]
Hi Richard,

Apologies, have been out of pocket for a bit.

Definitely fine to close this, I will take a look at the updated version and provide feedback upon my testing.

Thanks for all the efforts here!
