### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by henryfrith** [0x111/servicenow-instance-wakeup#21]
Login successful!
Detecting the wakeup button element to determine if we are on the developer portal homepage...
could not find shadow element (header status bar): context deadline exceeded

I am new to docker so this maybe user error. Command I ran:
docker run -e USERNAME=admin@mydomain.com -e PASSWORD=password ruthless/servicenow-instance-wakeup

**Comment by 0x111** [comment]
Hi!
Unfortunately, we have an issue with the docker container. See this issue for a temporary solution https://github.com/0x111/servicenow-instance-wakeup/issues/19
If you simply use the binary standalone and not inside the docker, the app works as expected!

I will close this in favor of #19
