### ISSUE TITLE
Could not find shadow element

### ISSUE THREAD

**Issue by termlen0** [0x111/servicenow-instance-wakeup#29]
Hello,
I wanted to alert you that the program seems to be erroring out with the following output:
```
Filled password field with your password ******
Clicking the submit button...
Clicked Submit button
Login successful!
Detecting the wakeup button element to determine if we are on the developer portal homepage...
could not find shadow element (header status bar): context deadline exceeded
```
Let me know if there's additional logs or troubleshooting I can provide to help.

**Comment by 0x111** [comment]
I will check this soon, thanks for reporting!

**Comment by 0x111** [comment]
Sorry for the late reply.
I did a research on this topic, seems like now, after someone logs in to the developer portal, they are running an autowakeup for the instance that has been asleep/hibernated before.
So technically it is enough to log in now, that is why it is not finding the shadow element.

Nevertheless the instance should be awake, I am thinking that removing the last "push of the button", should be good enough to fix this.

Can you confirm or deny this @termlen0 please?
