### ISSUE TITLE
how to get it working

### ISSUE THREAD

**Issue by kcferguson1** [0x111/servicenow-instance-wakeup#3]
im new to Go language .. how to get this working, basic steps would be appreciated.

**Comment by cheipol** [comment]
go to https://golang.org/ install it and follow the instructions

**Comment by 0x111** [comment]
Hi @kcferguson1! This is something out of the scope of support given for this app. To use this, you need to simply download the binaries, follow the instructions in the README file and run the software. For the project itself, we are using vgo, so you only need to clone/download the source code and run `go get` and then `go build` which results in a binary and then you can run your own version. But building from source is for those "powerusers" who do want to make modifications or have their own version built from this.

I will close this issue for now, if you will have some problems with running the application and it's functionality, please create a new issue. Thanks.
