### ISSUE TITLE
Searching for the .logo element...

### ISSUE THREAD

**Issue by vik-patel** [0x111/servicenow-instance-wakeup#39]
not working for me

**Comment by 0x111** [comment]
Hi @vik-patel,
Thanks for reporting, it looks like they've finally changed the developer SSO login to the "new" version. I will need to adjust the flow now, I will also enhance the logic for the process like #38

**Comment by 0x111** [comment]
@vik-patel The latest release v0.5.3 should fix this issue.
Docker images have been tagged as latest and v0.5.3

**Comment by vik-patel** [comment]
thx ... works!
