### ISSUE TITLE
Parameters not working

### ISSUE THREAD

**Issue by cheipol** [0x111/servicenow-instance-wakeup#4]
Hi, 
I cant get the cli parameters work.
If I launch the program with parameters and a config.file, it takes the data from the config file instead of the one from the parameters.
If I launch the program with parameters and deleting the config.file it raise an error saying that you need a config file.

Thanks!

PS: Thanks for this program, its really usefull! ;)

**Comment by 0x111** [comment]
Thanks for using the app. You are probably right. Right now, after parsing the flags from the cli, the app reads the config file, which would then result in rewriting some parameters which may have been defined previously in the CLI flags. I will update the app to have a way to tell if we wan't to use CLI flags or config parameters. I will get back to you soon.

**Comment by 0x111** [comment]
@cheipol could you please review and confirm if this works now? See the new version for reference please.

I introduced a new flag `-config`, you can set the path to the config file here or just simply the name of the config file like `config.json` if it is in the current directory and it will get loaded. If the `config` is set, we will only load the config and not the cli parameters and vice versa (if the `config` flag is not set, we only use the cli parameters).

https://github.com/0x111/servicenow-instance-wakeup/releases/tag/v0.3

**Comment by cheipol** [comment]
works perfect! thanks!!!
