### ISSUE TITLE
How to run it in a Windows machine

### ISSUE THREAD

**Issue by RahmanM** [0x111/servicenow-instance-wakeup#44]
Hi there,

Is there an executeable or something to use this in a Windows machine? What are the steps to use it in a windows machine without the Docker way?

many thanks

**Comment by 0x111** [comment]
Absolutely, you need the exe file from here.

https://github.com/0x111/servicenow-instance-wakeup/releases/tag/v0.6

After downloading, follow the instructions from read me.

**Comment by RahmanM** [comment]
Thank you very much. Appreicated.

**Comment by 0x111** [comment]
And just so we are clear, if you do not want to use docker, you will need to have a chrome/chromium browser installed on your system, so the app can use that.

**Comment by RahmanM** [comment]
Thank you.

Regards,


Rahman
