### ISSUE TITLE
could not find start building button: context deadline exceeded

### ISSUE THREAD

**Issue by papseddy** [0x111/servicenow-instance-wakeup#45]
Hi, 

First of all thanks for your code, its fantastic. 

I dont know what i missed but its not working for me. I got below error but i remember after several hits it got successfull. 

But its not working every time. Moreover Just for your reference. 

```
ubuntu@dev:~$ docker run -e USERNAME='*****@*****' -e PASSWORD='*****@*****' ruthless/servicenow-instance-wakeup:v0.6 -e DEBUG='true' -e HEADLESS='true' -e TIMEOUT='180'
2023/06/07 11:02:28 Starting the app with debug=false/headless=true/account='*****@*****'
Successfully set the viewport...
Navigating to the webpage: https://developer.servicenow.com/userlogin.do?relayState=https%3A%2F%2Fdeveloper.servicenow.com%2Fdev.do%23!%2Fhome%3Fwu%3Dtrue
Successfully navigated to the webpage...
Searching for the #logo-now element...
Found #logo-now element
Filling out the username field...
Filled username field with '*****@*****'
Clicking the next button...
Clicked Next button
Searching for the password field...
Found password field
Filling out the password field...
Filled password field with your password ******
Clicking the Sign In button...
Clicked Sign In button
Login successful!
Setting cookies to pre-confirm cookie modal!
Cookies set!
could not find start building button: context deadline exceeded
```

Thanks in advance. 
//papseddy

**Comment by 0x111** [comment]
I will check this again hopefully this week with my credentials if there are any problems.

If you notice any additional information that might help me then don't hesitate to post it. Thanks

**Comment by papseddy** [comment]
Thanks for quick response... sure.. if i found any missing or changes in details i will post in comment.

**Comment by papseddy** [comment]
Just a wild thought.. does scripts required any specific port to be open for incoming or outgoing?

Thanks in advance.

**Comment by 0x111** [comment]
Not really, if your docker is able to access the internet, then you would not need any extra portforwarding. The app is only opening webpages and simulating what you would usually manually do.

I am waiting for my instance to go to sleep now, so I can check this.

**Comment by 0x111** [comment]
I just tried it, for me it works without an issue.

I have a few questions though.
1. Do you already have an instance requested right now that is in hibernated mode when you are trying to run the app? (the instance has to be ideally hibernating)
2. Do you maybe have a slow network of some kind, thus you need to raise the timeout for it to work properly? (it could be that the site is still loading, that is the reason why it can't find the button)

I ran the command below:
<details>
  <summary>Command and log</summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
```zsh
$ docker run -e USERNAME='account@mail.tld' -e PASSWORD='mypassword' ruthless/servicenow-instance-wakeup:v0.6 -e DEBUG='true' -e HEADLESS='true' -e TIMEOUT='180'
2023/06/09 14:30:52 Starting the app with debug=false/headless=true/account=account@mail.tld
Successfully set the viewport...
Navigating to the webpage: https://developer.servicenow.com/userlogin.do?relayState=https%3A%2F%2Fdeveloper.servicenow.com%2Fdev.do%23!%2Fhome%3Fwu%3Dtrue
Successfully navigated to the webpage...
Searching for the #logo-now element...
Found #logo-now element
Filling out the username field...
Filled username field with account@mail.tld
Clicking the next button...
Clicked Next button
Searching for the password field...
Found password field
Filling out the password field...
Filled password field with your password ******
Clicking the Sign In button...
Clicked Sign In button
Login successful!
Setting cookies to pre-confirm cookie modal!
Cookies set!
Start building button found
Instance wakeup initiated successfully, your instance should be awake pretty soon!
```
  
</details>

**Comment by papseddy** [comment]
Hi Thanks for quick help man.. 

I was digging rabbit hole, and found there was network port problem. After you suggest i make a fresh VM with proper internet access and look like it working.

Really apricate your help man.. 

Keep doing good work. 👍

**Comment by 0x111** [comment]
Great! I will close this. Feel free to report issues or changes if you find any! Thanks

**Comment by papseddy** [comment]
Hi, It was perfectly work find, i tried and it worked. But all sudden it start working and give me same error. can you please check from your end. Is that working for you?

Thanks in advance.

**Comment by 0x111** [comment]
I will check it this week, but I don't use the app too much lately because I need PDIs less. It also could be very easily that Servicenow changed some things - again - as they do every two or three releases.

**Comment by papseddy** [comment]
Hi, 

Did you get chance? 

Advance Thanks.

**Comment by 0x111** [comment]
Not yet, sorry. I will try it next week

**Comment by papseddy** [comment]
Hi, Did you get chance to check this?

Thanks.

**Comment by 0x111** [comment]
Hello,

It could be related to this PR: https://github.com/0x111/servicenow-instance-wakeup/pull/46

I am waiting for an instance to go sleep now so I can check. Then I will release a new version

**Comment by 0x111** [comment]
Can you try the new version v0.7 from docker hub or github packages please @papseddy? If correct details are provided, the instance wakes up without issue this time.

Thank you and sorry for the delay.

**Comment by papseddy** [comment]
Hi Richard @0x111 , 

Here is output. Look like i am not in luck. Or am i missing something in command line. 

```
ubuntu@localhost:~$ docker run -e USERNAME='example@example.com' -e PASSWORD='passwrd' ghcr.io/0x111/servicenow-instance-wakeup:v0.7 -e DEBUG='true' -e HEADLESS='true'
Unable to find image 'ghcr.io/0x111/servicenow-instance-wakeup:v0.7' locally
v0.7: Pulling from 0x111/servicenow-instance-wakeup
759700526b78: Pull complete
0d9be1a78817: Pull complete
d06868d36170: Pull complete
6da4d23eec64: Pull complete
af75c563517a: Pull complete
aaaf8f9e2c65: Pull complete
Digest: sha256:192bcb454c76e57b930b5885a62343748b83c1421111b05b1f00118f95a771ef
Status: Downloaded newer image for ghcr.io/0x111/servicenow-instance-wakeup:v0.7
2023/12/18 14:26:32 Starting the app with debug=false/headless=true/account=example@example.com
Successfully set the viewport...
Navigating to the webpage: https://developer.servicenow.com/userlogin.do?relayState=https%3A%2F%2Fdeveloper.servicenow.com%2Fdev.do%23!%2Fhome%3Fwu%3Dtrue
Successfully navigated to the webpage...
Searching for the #logo-now element...
Found #logo-now element
Filling out the username field...
Filled username field with example@example.com
Clicking the next button...
Clicked Next button
Searching for the password field...
Found password field
Filling out the password field...
Filled password field with your password ******
Clicking the Sign In button...
Clicked Sign In button
Login successful!
Setting cookies to pre-confirm cookie modal!
Cookies set!
could not find start building button: context deadline exceeded
```
